### ISSUE TITLE
Dev service

### ISSUE THREAD

**Issue by EzraAmes** [diamondTheRat/haram-script#1]
Hello. 
I hope you are doing well.
My name is Ezra Ames and I found you on Github. 
I want to discuss something with you but when is convenient to communicate with you?

**Comment by diamondTheRat** [comment]
Hi if its possible I would like to continue this conversation on discord, my user is dia_rat.
If you can't do that we can still discuss here but I can't guarantee fast response times.

**Comment by EzraAmes** [comment]
Just send friend request. brainartfu
